import { PRODUCTS, type Product, asExample } from './data';
import { STARTER_INFO } from './productInfo';

/* App templates (Android, iPhone & iPad, web apps, desktop apps) live beside the websites, not inside PRODUCTS, so every website-only screen (home ring, quiz, categories) stays untouched. */
export type Platform = 'web' | 'android' | 'ios' | 'webapp' | 'desktop' | 'digital';
export type AppPlatform = Exclude<Platform, 'web'>;
export const platformOf = (p: Product): Platform => p.platform ?? 'web';
export const isApp = (p: Product) => platformOf(p) !== 'web';

/* How an order is delivered: 'store' = built and sent to the buyer's own store account, 'host' = deployed on the buyer's domain, 'installer' = installers for the buyer's computers. */
export type Delivery = 'store' | 'host' | 'installer' | 'download';

export const SHELVES: Record<AppPlatform, { slug: string; label: string; badge: string; tone: 'mint' | 'rose' | 'violet' | 'gold' | 'cobalt'; delivery: Delivery; store?: string; noun: string }> = {
  android: { slug: 'android', label: 'Android apps', badge: 'Android', tone: 'mint', delivery: 'store', store: 'Google Play', noun: 'Android app' },
  ios: { slug: 'ios', label: 'iPhone & iPad apps', badge: 'iPhone & iPad', tone: 'rose', delivery: 'store', store: 'App Store', noun: 'iPhone & iPad app' },
  webapp: { slug: 'web', label: 'Web apps', badge: 'Web app', tone: 'violet', delivery: 'host', noun: 'web app' },
  desktop: { slug: 'desktop', label: 'Desktop apps', badge: 'Desktop', tone: 'gold', delivery: 'installer', noun: 'desktop app' },
  digital: { slug: 'digital', label: 'Digital products', badge: 'Digital', tone: 'cobalt', delivery: 'download', noun: 'digital product' },
};
export const SLUG_TO_PLATFORM: Record<string, AppPlatform> = { android: 'android', ios: 'ios', web: 'webapp', desktop: 'desktop', digital: 'digital' };
export const shelfHref = (pl: Platform) => (pl === 'web' ? '/browse' : `/apps/${SHELVES[pl].slug}`);
export const shelfLabel = (pl: Platform) => (pl === 'web' ? 'Websites' : SHELVES[pl].label);
export const deliveryOf = (p: Product): Delivery | null => {
  const pl = platformOf(p);
  return pl === 'web' ? null : SHELVES[pl].delivery;
};
export const storeOf = (p: Product): string => {
  const pl = platformOf(p);
  return pl === 'android' || pl === 'ios' ? (SHELVES[pl].store ?? '') : '';
};
export const PLATFORM_NAME: Record<Platform, string> = { web: 'Website', android: 'Android app', ios: 'iPhone & iPad app', webapp: 'Web app', desktop: 'Desktop app', digital: 'Digital product' };
export const STORE_NAME: Record<'android' | 'ios', string> = { android: 'Google Play', ios: 'App Store' };

export const APP_CATS = ['Fitness', 'Food', 'Productivity', 'Travel', 'Finance', 'Education', 'Business', 'Utilities'];
/* Digital products: delivered as files or access, never put live on a domain. */
export const DIGITAL_CATS = ['Figma kits', 'No-code templates', 'Plugins', 'Scripts', 'AI automations', 'Chatbots', 'AI prompts', 'Video templates'];
export const DIGITAL_TOOLS = [
  'Figma',
  'Notion',
  'Webflow',
  'Framer',
  'WordPress',
  'Shopify',
  'n8n',
  'Make',
  'Zapier',
  'Python',
  'JavaScript',
  'ChatGPT',
  'Midjourney',
  'ComfyUI',
  'Premiere Pro',
  'After Effects',
  'CapCut',
  'Other',
];
/* Things a buyer cannot judge from a picture: the seller must show them working (a video, a view-only link or a sample result). */
/* A buyer cannot judge these from pictures alone. Prompts and video templates need sample results or a preview video. */
export const NEEDS_DEMO = ['Plugins', 'Scripts', 'AI automations', 'Chatbots', 'AI prompts', 'Video templates'];
export const catsFor = (pl: Platform) => (pl === 'digital' ? DIGITAL_CATS : APP_CATS);
export const toolsFor = (pl: Platform) => (pl === 'digital' ? DIGITAL_TOOLS : STACKS);
export const STACKS = ['Flutter', 'React Native', 'Kotlin', 'Swift', 'SwiftUI', 'Java', 'Unity', 'Next.js', 'React', 'Vue', 'Laravel', 'Electron', 'Tauri', '.NET', 'Python', 'Other'];
export const APP_FEATURES: { key: string; label: string }[] = [
  { key: 'login', label: 'Sign-in' },
  { key: 'pay', label: 'Payments' },
  { key: 'push', label: 'Notifications' },
  { key: 'offline', label: 'Works offline' },
  { key: 'maps', label: 'Maps' },
  { key: 'teams', label: 'Team accounts' },
  { key: 'api', label: 'API' },
  { key: 'export', label: 'Import and export' },
  { key: 'sync', label: 'Cloud sync' },
  { key: 'updates', label: 'Auto-update' },
  { key: 'ai', label: 'Uses AI' },
  { key: 'nocode', label: 'No code needed' },
  { key: 'docs', label: 'Setup guide' },
  { key: 'support', label: 'Seller support' },
];

type Spec = NonNullable<Product['app']>;
const A = (
  id: string,
  name: string,
  platform: AppPlatform,
  cat: string,
  price: number,
  seller: string,
  rating: number,
  reviews: number,
  sold: number,
  days: number,
  added: string,
  stack: string,
  tag: string,
  desc: string,
  inc: string[],
  does: string[],
  app: Spec,
): Product => ({ id, name, theme: 'bio', cat, price, seller, rating, reviews, sold, days, tag, desc, inc, added, does, platform, stack, app });

export const APPS: Product[] = [
  A(
    'fittrack',
    'FitTrack',
    'android',
    'Fitness',
    79,
    'Leo Park',
    4.7,
    64,
    96,
    3,
    '2026-10-04',
    'Kotlin',
    'Workout and step tracker',
    'A clean fitness app with workout plans, a daily step ring and progress charts. Rebrand it and publish it under your own name.',
    ['Workout plans and timer', 'Daily step and calorie ring', 'Weekly progress charts', 'Sign-in with email or Google', 'Push reminders', 'Works offline'],
    ['login', 'push', 'offline'],
    {
      accent: '#0E9F76',
      bg: '#F2FBF8',
      ink: '#07271E',
      glyph: 'F',
      headline: 'Today',
      metric: { label: 'Steps', value: '8,420', pct: 0.78 },
      rows: [
        ['Morning run', '32 min'],
        ['Strength A', '45 min'],
        ['Evening walk', '20 min'],
      ],
      bars: [40, 64, 52, 80, 70, 92, 60],
      cta: 'Start workout',
      tabs: ['Home', 'Plans', 'Stats', 'You'],
    },
  ),
  A(
    'quickbite',
    'QuickBite',
    'android',
    'Food',
    129,
    'Hana Sato',
    4.8,
    41,
    58,
    3,
    '2026-10-02',
    'Flutter',
    'Food ordering for one restaurant',
    'An ordering app for a restaurant or small chain: menu, cart, card payments and live order status.',
    ['Menu with photos and options', 'Cart and card checkout', 'Live order status', 'Sign-in and saved addresses', 'Push notifications', 'Admin menu editor'],
    ['login', 'pay', 'push', 'maps'],
    {
      accent: '#E4572E',
      bg: '#FFF6EA',
      ink: '#2B1608',
      glyph: 'Q',
      headline: 'Order now',
      metric: { label: 'Delivery in', value: '25 min', pct: 0.6 },
      rows: [
        ['Saffron bowl', '$11'],
        ['Grilled wrap', '$9'],
        ['Lemon soda', '$3'],
      ],
      bars: [30, 55, 80, 60, 90, 70, 48],
      cta: 'Checkout',
      tabs: ['Menu', 'Cart', 'Orders', 'You'],
    },
  ),
  A(
    'habitloop',
    'HabitLoop',
    'android',
    'Productivity',
    39,
    'Noor Rahman',
    4.5,
    88,
    210,
    1,
    '2026-09-20',
    'React Native',
    'Daily habit tracker',
    'A simple habit tracker with streaks, reminders and a calm weekly view. Small, fast and easy to rebrand.',
    ['Habits with streaks', 'Daily reminders', 'Weekly and monthly view', 'Dark and light theme', 'Works offline', 'Backup to the cloud'],
    ['push', 'offline'],
    {
      accent: '#7A3CFF',
      bg: '#F6F2FF',
      ink: '#1B0B3D',
      glyph: 'H',
      headline: 'Habits',
      metric: { label: 'Best streak', value: '21 days', pct: 0.7 },
      rows: [
        ['Drink water', 'Done'],
        ['Read 20 pages', 'Done'],
        ['Stretch', 'Today'],
      ],
      bars: [60, 60, 75, 40, 90, 85, 95],
      cta: 'Add a habit',
      tabs: ['Today', 'Week', 'Stats', 'More'],
    },
  ),
  A(
    'notenest',
    'NoteNest',
    'ios',
    'Productivity',
    59,
    'Priya Nair',
    4.9,
    52,
    143,
    2,
    '2026-10-05',
    'SwiftUI',
    'Notes with folders and search',
    'A fast notes app with folders, tags, search and iCloud sync, built natively in SwiftUI.',
    ['Notes, folders and tags', 'Instant search', 'iCloud sync', 'Face ID lock', 'Home screen widget', 'Dark mode'],
    ['login', 'offline', 'push'],
    {
      accent: '#F0A500',
      bg: '#FFFBEF',
      ink: '#2A1E00',
      glyph: 'N',
      headline: 'Notes',
      metric: { label: 'Notes today', value: '12', pct: 0.5 },
      rows: [
        ['Meeting ideas', 'Work'],
        ['Grocery list', 'Home'],
        ['Trip plan', 'Travel'],
      ],
      bars: [20, 45, 30, 70, 55, 80, 66],
      cta: 'New note',
      tabs: ['Notes', 'Folders', 'Search', 'Settings'],
    },
  ),
  A(
    'trippal',
    'TripPal',
    'ios',
    'Travel',
    149,
    'Arif Hossain',
    4.7,
    29,
    44,
    3,
    '2026-09-26',
    'SwiftUI',
    'Travel planner',
    'Plan a trip day by day with maps, bookings and a shared packing list. Ready for a travel brand or a creator.',
    ['Day by day itinerary', 'Maps and saved places', 'Shared packing list', 'Booking confirmations', 'Works offline', 'Sign in with Apple'],
    ['login', 'maps', 'offline'],
    {
      accent: '#0891B2',
      bg: '#F0FBFE',
      ink: '#07262E',
      glyph: 'T',
      headline: 'Lisbon trip',
      metric: { label: 'Days to go', value: '12', pct: 0.4 },
      rows: [
        ['Day 1 · Alfama', '4 stops'],
        ['Day 2 · Belem', '3 stops'],
        ['Day 3 · Sintra', '2 stops'],
      ],
      bars: [35, 50, 62, 44, 70, 58, 82],
      cta: 'Add a stop',
      tabs: ['Trips', 'Map', 'Pack', 'You'],
    },
  ),
  A(
    'spliteasy',
    'SplitEasy',
    'ios',
    'Finance',
    99,
    'Tomás Rivera',
    4.6,
    37,
    71,
    2,
    '2026-09-12',
    'React Native',
    'Split bills with friends',
    'Add an expense, split it between friends and see who owes what. Simple, friendly and ready for payments.',
    ['Groups and shared expenses', 'Fair split and settle up', 'Receipt photos', 'Payments hand-off', 'Push reminders', 'Multiple currencies'],
    ['login', 'pay', 'push'],
    {
      accent: '#2B3DFF',
      bg: '#F4F6FF',
      ink: '#0F1330',
      glyph: 'S',
      headline: 'Roommates',
      metric: { label: 'You are owed', value: '$84.50', pct: 0.66 },
      rows: [
        ['Groceries', '$62'],
        ['Internet', '$30'],
        ['Dinner out', '$45'],
      ],
      bars: [50, 35, 60, 80, 45, 70, 55],
      cta: 'Settle up',
      tabs: ['Groups', 'Add', 'Activity', 'You'],
    },
  ),
  A(
    'taskboard',
    'TaskBoard',
    'webapp',
    'Productivity',
    189,
    'Priya Nair',
    4.8,
    46,
    62,
    3,
    '2026-10-05',
    'Next.js',
    'Team task board',
    'A Kanban style task board for small teams: boards, cards, comments and invites. Deployed on your own domain under your brand.',
    ['Boards, lists and cards', 'Comments and mentions', 'Team invites and roles', 'Sign-in with email or Google', 'Stripe-ready plans page', 'Admin dashboard'],
    ['login', 'teams', 'pay', 'api'],
    {
      accent: '#7A3CFF',
      bg: '#F6F2FF',
      ink: '#1B0B3D',
      glyph: 'T',
      headline: 'Sprint board',
      metric: { label: 'Done this week', value: '34', pct: 0.72 },
      rows: [
        ['Design review', 'Today'],
        ['Fix login bug', 'In progress'],
        ['Launch email', 'Backlog'],
      ],
      bars: [30, 55, 70, 62, 85, 78, 92],
      cta: 'New card',
      tabs: ['Board', 'Team', 'Reports', 'Settings'],
    },
  ),
  A(
    'invoicedesk',
    'InvoiceDesk',
    'webapp',
    'Business',
    229,
    'Arif Hossain',
    4.7,
    33,
    41,
    3,
    '2026-09-28',
    'React',
    'Invoices and clients',
    'Create invoices, track who has paid and see monthly income. A small business web app with a client portal.',
    ['Invoices and PDF export', 'Client list and portal', 'Payment status tracking', 'Monthly income charts', 'Sign-in and team roles', 'Email reminders'],
    ['login', 'pay', 'export', 'api'],
    {
      accent: '#0E9F76',
      bg: '#F2FBF8',
      ink: '#07271E',
      glyph: 'I',
      headline: 'Overview',
      metric: { label: 'Paid this month', value: '$8,420', pct: 0.68 },
      rows: [
        ['Harbor Cafe', 'Paid'],
        ['Studio Nine', 'Due'],
        ['Alvarez Dental', 'Paid'],
      ],
      bars: [45, 52, 40, 70, 66, 88, 74],
      cta: 'New invoice',
      tabs: ['Overview', 'Invoices', 'Clients', 'Reports'],
    },
  ),
  A(
    'formforge',
    'FormForge',
    'webapp',
    'Business',
    119,
    'Tomás Rivera',
    4.5,
    28,
    55,
    2,
    '2026-09-18',
    'Vue',
    'Form and survey builder',
    'Drag and drop forms and surveys with answers collected in one place. Embed anywhere or share a link.',
    ['Drag and drop form builder', 'Answers dashboard', 'CSV export', 'Embed code and share link', 'Sign-in and workspaces', 'Webhook and API'],
    ['login', 'export', 'api', 'teams'],
    {
      accent: '#E4572E',
      bg: '#FFF6EA',
      ink: '#2B1608',
      glyph: 'F',
      headline: 'Forms',
      metric: { label: 'Answers today', value: '128', pct: 0.55 },
      rows: [
        ['Customer survey', '86 answers'],
        ['Event signup', '42 answers'],
        ['Feedback form', '17 answers'],
      ],
      bars: [25, 40, 35, 60, 82, 55, 70],
      cta: 'New form',
      tabs: ['Forms', 'Answers', 'Share', 'Settings'],
    },
  ),
  A(
    'focustimer',
    'FocusTimer',
    'desktop',
    'Productivity',
    59,
    'Noor Rahman',
    4.8,
    51,
    120,
    2,
    '2026-10-03',
    'Electron',
    'Pomodoro timer for Windows and Mac',
    'A calm focus timer that lives in the menu bar and tray, with sessions, breaks and a daily summary.',
    ['Focus and break timer', 'Menu bar and tray icon', 'Daily and weekly summary', 'Sounds and notifications', 'Starts with the computer', 'Windows and macOS installers'],
    ['push', 'offline', 'updates'],
    {
      accent: '#E23C61',
      bg: '#FFF5F7',
      ink: '#2D0A14',
      glyph: 'F',
      headline: 'Focus',
      metric: { label: 'Next break in', value: '18:42', pct: 0.64 },
      rows: [
        ['Write report', '2 sessions'],
        ['Email', '1 session'],
        ['Design', '3 sessions'],
      ],
      bars: [30, 50, 45, 80, 70, 95, 60],
      cta: 'Start focus',
      tabs: ['Timer', 'Tasks', 'Stats', 'Settings'],
    },
  ),
  A(
    'clipvault',
    'ClipVault',
    'desktop',
    'Utilities',
    49,
    'Samir Khan',
    4.6,
    39,
    88,
    1,
    '2026-09-22',
    'Tauri',
    'Clipboard history manager',
    'Keeps everything you copy, searchable and pinned, with a shortcut to paste from history. Small, fast and private.',
    ['Clipboard history', 'Search and pin items', 'Global shortcut', 'Stays on your computer', 'Light and dark theme', 'Windows, macOS and Linux builds'],
    ['offline', 'export', 'updates'],
    {
      accent: '#2B3DFF',
      bg: '#F4F6FF',
      ink: '#0F1330',
      glyph: 'C',
      headline: 'History',
      metric: { label: 'Items saved', value: '412', pct: 0.5 },
      rows: [
        ['Meeting link', 'Pinned'],
        ['Invoice no. 1042', '2 min ago'],
        ['Address', '1 hour ago'],
      ],
      bars: [20, 35, 50, 40, 66, 58, 80],
      cta: 'Paste',
      tabs: ['All', 'Pinned', 'Search', 'Settings'],
    },
  ),
  A(
    'ledgerlite',
    'LedgerLite',
    'desktop',
    'Finance',
    139,
    'Hana Sato',
    4.7,
    24,
    36,
    3,
    '2026-09-08',
    '.NET',
    'Offline bookkeeping',
    'Simple bookkeeping that works offline: income, expenses, categories and monthly reports saved on your own computer.',
    ['Income and expenses', 'Categories and tags', 'Monthly reports', 'CSV and PDF export', 'Works fully offline', 'Windows installer'],
    ['offline', 'export', 'sync'],
    {
      accent: '#0891B2',
      bg: '#F0FBFE',
      ink: '#07262E',
      glyph: 'L',
      headline: 'Ledger',
      metric: { label: 'Balance', value: '$12,380', pct: 0.7 },
      rows: [
        ['Office rent', '-$900'],
        ['Client payment', '+$2,400'],
        ['Software', '-$49'],
      ],
      bars: [50, 42, 60, 48, 75, 66, 85],
      cta: 'Add entry',
      tabs: ['Ledger', 'Reports', 'Categories', 'Settings'],
    },
  ),
  A(
    'saas-ui-kit',
    'SaaS UI Kit',
    'digital',
    'Figma kits',
    39,
    'Emily Chen',
    4.9,
    58,
    143,
    1,
    '2026-10-05',
    'Figma',
    'Dashboard and landing screens for Figma',
    'Over 120 screens and 300 components for a SaaS product: dashboards, tables, onboarding and a full marketing site. Auto layout and variables are set up.',
    ['120 screens', '300 components with variants', 'Light and dark themes', 'Design tokens as variables', 'Short video tour'],
    ['docs', 'nocode'],
    {
      accent: '#7A3CFF',
      bg: '#F4EEFF',
      ink: '#1E0F3D',
      glyph: 'F',
      headline: 'Figma kit',
      metric: { label: 'Screens', value: '120', pct: 0.8 },
      rows: [
        ['saas-ui-kit.fig', '48 MB'],
        ['Icons.svg', '2 MB'],
        ['Guide.pdf', '1 MB'],
      ],
      bars: [40, 70, 55, 90, 65],
      cta: 'Open in Figma',
      tabs: ['Files', 'Preview', 'Guide'],
    },
  ),
  A(
    'notion-crm',
    'Notion Client CRM',
    'digital',
    'No-code templates',
    19,
    'Noor Rahman',
    4.7,
    112,
    380,
    1,
    '2026-10-02',
    'Notion',
    'A simple CRM for freelancers',
    'A Notion workspace for leads, clients, projects and invoices, with views for the week, the pipeline and what is overdue. Duplicate it and start.',
    ['Leads and pipeline board', 'Clients and projects', 'Invoice tracker', 'Weekly dashboard', 'Setup guide'],
    ['nocode', 'docs'],
    {
      accent: '#0F1330',
      bg: '#F5F6FA',
      ink: '#0F1330',
      glyph: 'N',
      headline: 'Notion',
      metric: { label: 'Open leads', value: '24', pct: 0.5 },
      rows: [
        ['Pipeline', 'Board'],
        ['Clients', 'Table'],
        ['Invoices', 'List'],
      ],
      bars: [30, 60, 45, 80, 70],
      cta: 'Duplicate',
      tabs: ['Files', 'Preview', 'Guide'],
    },
  ),
  A(
    'webflow-agency',
    'Agency Webflow Template',
    'digital',
    'No-code templates',
    59,
    'Aisha Rahman',
    4.8,
    37,
    61,
    1,
    '2026-09-28',
    'Webflow',
    'Agency site with a CMS',
    'A clean agency site for Webflow with case studies, a blog and a contact form, all editable from the CMS. Clone it to your account and publish.',
    ['Home, work, blog and contact pages', 'CMS for case studies and posts', 'Animations set up', 'Mobile ready', 'Setup guide'],
    ['nocode', 'docs'],
    {
      accent: '#2B3DFF',
      bg: '#F1F3FF',
      ink: '#0F1330',
      glyph: 'W',
      headline: 'Webflow',
      metric: { label: 'Pages', value: '12', pct: 0.6 },
      rows: [
        ['Clone link', 'Private'],
        ['Guide.pdf', '2 MB'],
        ['Assets.zip', '14 MB'],
      ],
      bars: [50, 65, 40, 85, 60],
      cta: 'Clone',
      tabs: ['Files', 'Preview', 'Guide'],
    },
  ),
  A(
    'wp-booking',
    'Booking Plugin for WordPress',
    'digital',
    'Plugins',
    49,
    'Priya Nair',
    4.6,
    44,
    97,
    1,
    '2026-09-25',
    'WordPress',
    'Appointments with email reminders',
    'A lightweight booking plugin: services, opening hours, a booking form shortcode, email confirmations and a simple calendar in the dashboard.',
    ['Services and opening hours', 'Booking form shortcode', 'Email confirmations and reminders', 'Calendar in the dashboard', 'Readme and install steps'],
    ['docs', 'support'],
    {
      accent: '#0E9F76',
      bg: '#F2FBF8',
      ink: '#07271E',
      glyph: 'B',
      headline: 'Plugin',
      metric: { label: 'Bookings today', value: '9', pct: 0.45 },
      rows: [
        ['booking.zip', '420 KB'],
        ['readme.txt', '6 KB'],
        ['license.txt', '1 KB'],
      ],
      bars: [35, 55, 70, 50, 85],
      cta: 'Install',
      tabs: ['Files', 'Preview', 'Guide'],
    },
  ),
  A(
    'n8n-leads',
    'Lead Capture to CRM (n8n)',
    'digital',
    'AI automations',
    29,
    'Samir Khan',
    4.8,
    73,
    211,
    1,
    '2026-10-04',
    'n8n',
    'Forms to CRM with an AI summary',
    'An n8n workflow that takes a form submission, writes a short AI summary, scores the lead and adds it to your CRM and Slack. Import the file and add your keys.',
    ['n8n workflow file', 'AI summary and lead score', 'CRM and Slack steps', 'Setup guide with screenshots', 'Free fixes for 30 days'],
    ['ai', 'docs', 'support'],
    {
      accent: '#E4572E',
      bg: '#FFF6EA',
      ink: '#2B1608',
      glyph: 'n',
      headline: 'Automation',
      metric: { label: 'Runs a day', value: '240', pct: 0.7 },
      rows: [
        ['workflow.json', '38 KB'],
        ['setup-guide.pdf', '3 MB'],
        ['sample-data.csv', '4 KB'],
      ],
      bars: [45, 60, 75, 55, 90],
      cta: 'Import',
      tabs: ['Files', 'Preview', 'Guide'],
    },
  ),
  A(
    'make-invoices',
    'Invoice Reminders (Make)',
    'digital',
    'AI automations',
    25,
    'Hana Sato',
    4.7,
    51,
    134,
    1,
    '2026-09-30',
    'Make',
    'Chase late invoices automatically',
    'A Make scenario that checks your invoices every morning and sends friendly, polite reminders that get firmer over time. Works with Google Sheets or Stripe.',
    ['Make scenario blueprint', 'Three reminder emails', 'Google Sheets and Stripe options', 'Setup guide', 'Free fixes for 30 days'],
    ['ai', 'docs', 'support'],
    {
      accent: '#7A3CFF',
      bg: '#F4EEFF',
      ink: '#1E0F3D',
      glyph: 'M',
      headline: 'Scenario',
      metric: { label: 'Reminders sent', value: '56', pct: 0.55 },
      rows: [
        ['blueprint.json', '22 KB'],
        ['emails.docx', '14 KB'],
        ['guide.pdf', '2 MB'],
      ],
      bars: [30, 50, 65, 80, 60],
      cta: 'Import',
      tabs: ['Files', 'Preview', 'Guide'],
    },
  ),
  A(
    'support-bot',
    'Support Chatbot Widget',
    'digital',
    'Chatbots',
    79,
    'Lucas Ferreira',
    4.9,
    29,
    48,
    2,
    '2026-10-01',
    'JavaScript',
    'A chatbot trained on your own help pages',
    'An embeddable chat widget that answers from your help pages and hands over to email when it is not sure. Bring your own AI key. Includes the widget, a small server and a guide.',
    ['Chat widget (one script tag)', 'Small server for your AI key', 'Answers from your own pages', 'Hand-over to email', 'Setup guide'],
    ['ai', 'docs', 'support'],
    {
      accent: '#0891B2',
      bg: '#F0FBFE',
      ink: '#07262E',
      glyph: 'C',
      headline: 'Chatbot',
      metric: { label: 'Chats answered', value: '86%', pct: 0.86 },
      rows: [
        ['widget.js', '24 KB'],
        ['server.zip', '180 KB'],
        ['guide.pdf', '2 MB'],
      ],
      bars: [40, 55, 80, 70, 92],
      cta: 'Embed',
      tabs: ['Files', 'Preview', 'Guide'],
    },
  ),
  A(
    'seo-audit',
    'Bulk SEO Audit Script',
    'digital',
    'Scripts',
    35,
    'Fatima Zahra',
    4.6,
    33,
    76,
    1,
    '2026-09-18',
    'Python',
    'Check a whole site in one run',
    'A Python script that crawls a site and writes a spreadsheet of titles, descriptions, headings, broken links and slow pages. Runs on your own computer.',
    ['Python script', 'Spreadsheet report', 'Broken links and slow pages', 'Readme with examples', 'Free fixes for 30 days'],
    ['docs', 'support'],
    {
      accent: '#E23C61',
      bg: '#FFF5F7',
      ink: '#2D0A14',
      glyph: 'S',
      headline: 'Script',
      metric: { label: 'Pages checked', value: '1,240', pct: 0.7 },
      rows: [
        ['seo_audit.py', '9 KB'],
        ['requirements.txt', '1 KB'],
        ['README.md', '4 KB'],
      ],
      bars: [50, 35, 70, 60, 80],
      cta: 'Run',
      tabs: ['Files', 'Preview', 'Guide'],
    },
  ),
]
  .map((p) => (STARTER_INFO[p.id] ? { ...p, ...STARTER_INFO[p.id] } : p))
  .map(asExample);

export const ALL_PRODUCTS: Product[] = [...PRODUCTS, ...APPS];
export const findAny = (id?: string | null) => ALL_PRODUCTS.find((p) => p.id === id);
export const appsFor = (platform: AppPlatform) => APPS.filter((p) => p.platform === platform);

/* Every "what it does" tag, web and app, so cards and the compare table can label any listing. */
export { FEATURES } from './data';
